// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test3_robobar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test3_robobar', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(907, 886)
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    vars["total"] = await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText()
    console.log("total=" + vars["total"])
    assert(vars["total"].toString() == "€1.25")
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    vars["total"] = await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText()
    console.log("total=" + vars['total'])
    assert(vars["total"].toString() == "€3.25")
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    vars["total"] = await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText()
    console.log("total=" + vars['total'])
    assert(vars["total"].toString() == "€6.25")
    //await driver.findElement(By.css(".btn-success")).click()
    //Script con wait
    await driver.wait(until.elementLocated(By.css(".btn-success"))).click();
    vars["total"] = await driver.findElement(By.css(".ng-scope:nth-child(1) > .ng-binding:nth-child(4)")).getText()
    console.log("Roba Cola total=" + vars['total'])
    assert(vars["total"].toString() == "€1.25")
    vars["total"] = await driver.findElement(By.css(".ng-scope:nth-child(2) > .ng-binding:nth-child(4)")).getText()
    console.log("Robo Beer total=" + vars['total'])
    assert(vars["total"].toString() == "€2.00")
    vars["total"] = await driver.findElement(By.css(".ng-scope:nth-child(3) > .ng-binding:nth-child(4)")).getText()
    console.log("Rob Wine total=" + vars['total'])
    assert(vars["total"].toString() == "€3.00")
    await driver.findElement(By.id("ageInput")).click()
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    await driver.findElement(By.css(".btn-success")).click()
  })
})
