// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test2_robobar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test2_robobar', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(907, 886)
    await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(1) > .ng-binding:nth-child(2)")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(1) > .ng-binding:nth-child(2)")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(2) > .ng-binding:nth-child(2)")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(1) > .ng-binding:nth-child(2)")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(2) > .ng-binding:nth-child(2)")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(3) > .ng-binding:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-success")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td:nth-child(1)")).click()
    await driver.findElement(By.id("ageInput")).click()
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    await driver.findElement(By.css(".btn-success")).click()
  })
})
