// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test1_robobar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test1_robobar', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(907, 886)
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    vars["total"] = await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText()
    console.log("total=vars["total"]")
    assert(vars["total"].toString() == "€1.25")
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    vars["total"] = await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText()
    console.log("total=vars["total"]")
    assert(vars["total"].toString() == "€3.25")
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    vars["total"] = await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText()
    console.log("total=vars["total"]")
    assert(vars["total"].toString() == "€6.25")
  })
})
